'use client';
import { useEffect, useState } from 'react';
import AdminLayout from '@/components/admin-layout';

type C = {id:number;brand_name:string;status:string;last_conversation_date:string;notes?:string;next_follow_up_date?:string};
export default function Page(){
const [items,setItems]=useState<C[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
const [form,setForm]=useState({brand_name:'',last_conversation_date:'',status:'New Lead',notes:'',next_follow_up_date:''});
const load=async()=>{setLoading(true); const r=await fetch('/api/collaborations'); const d=await r.json(); if(!r.ok){setError(d.error||'Failed');} else {setItems(d);} setLoading(false);}; useEffect(()=>{load();},[]);
const add=async(e:React.FormEvent)=>{e.preventDefault(); const r=await fetch('/api/collaborations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); if(r.ok){setForm({brand_name:'',last_conversation_date:'',status:'New Lead',notes:'',next_follow_up_date:''}); load();}};
const patch=async(id:number,body:Partial<C>)=>{await fetch(`/api/collaborations/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); load();};
const del=async(id:number)=>{await fetch(`/api/collaborations/${id}`,{method:'DELETE'}); load();};
return <AdminLayout><h1 className='text-2xl font-bold mb-4'>Collaborations CRM</h1><form onSubmit={add} className='bg-white p-3 border rounded mb-4 grid md:grid-cols-5 gap-2'><input className='border p-2 rounded' placeholder='Brand Name' value={form.brand_name} onChange={e=>setForm({...form,brand_name:e.target.value})} required /><input className='border p-2 rounded' type='date' value={form.last_conversation_date} onChange={e=>setForm({...form,last_conversation_date:e.target.value})} required /><input className='border p-2 rounded' type='date' value={form.next_follow_up_date} onChange={e=>setForm({...form,next_follow_up_date:e.target.value})}/><input className='border p-2 rounded' placeholder='Notes' value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button className='bg-slate-900 text-white rounded px-3'>Add</button></form>{loading?<p>Loading...</p>:error?<p className='text-red-600'>{error}</p>:<div className='bg-white rounded border overflow-x-auto'><table className='w-full'><thead><tr className='bg-slate-100'><th className='p-2 text-left'>Brand</th><th>Status</th><th>Last</th><th>Next Follow-up</th><th>Actions</th></tr></thead><tbody>{items.map(c=><tr key={c.id} className='border-t'><td className='p-2'>{c.brand_name}</td><td><select className='border rounded p-1' value={c.status} onChange={e=>patch(c.id,{status:e.target.value})}>{['New Lead','Contacted','Awaiting Response','Negotiating','Approved','Completed','Archived'].map(s=><option key={s}>{s}</option>)}</select></td><td>{c.last_conversation_date}</td><td>{c.next_follow_up_date||'-'}</td><td className='space-x-2'><button className='text-blue-600' onClick={()=>patch(c.id,{notes:prompt('Notes',c.notes||'')||c.notes})}>Edit notes</button><button className='text-red-600' onClick={()=>del(c.id)}>Delete</button></td></tr>)}</tbody></table></div>}</AdminLayout>}
